export { default as Home } from './Home.js';
export { default as NavbarComp } from './NavbarComp.js';
export { default as CheckoutForm } from './CheckoutForm.js';
export { default as LoginModal } from './Login.js';
export { default as RegisterModal } from './Register.js';
export { default as Albums } from './Albums';
export { default as PaginationComponent } from './PaginationComponent';
export { default as SingleAlbum } from './SingleAlbum.js';
export { default as FooterUnit } from './Footer.js';
export { default as Admin } from './Admin.js';
export { default as Orders } from './Orders.js';
export { default as OrdersAlbums } from './OrdersAlbums.js';
export { default as AlbumInformation } from './AlbumInformation.js'
export { default as AboutUs } from './AboutUs.js';
export { default as Contact } from './Contact.js';
