export { default as Home } from './Home.js';
export { default as NavbarComp } from './NavbarComp.js';
export { default as CheckoutForm } from './CheckoutForm.js';
export { default as LoginModal } from './Login.js';
export { default as RegisterModal } from './Register.js';
export { default as Albums } from './Albums.js'
export { default as PaginationComponent } from './PaginationComponent.js'
export { default as SingleAlbum } from './SingleAlbum.js';
export { default as FooterUnit } from './Footer.js';
export { default as Orders } from './Orders.js'